//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 03:11:25 PM EST 
//


package edu.bu.kuali.kc.award.printing.awardnotice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AnticipatedAmountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnticipatedAmountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProjectStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="AnticipatedDirectTotal" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="AnticipatedIndirectTotal" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="AnticipatedTotal" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ProjectEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnticipatedAmountType", propOrder = {
    "projectStartDate",
    "anticipatedDirectTotal",
    "anticipatedIndirectTotal",
    "anticipatedTotal",
    "projectEndDate"
})
public class AnticipatedAmountType {

    @XmlElement(name = "ProjectStartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar projectStartDate;
    @XmlElement(name = "AnticipatedDirectTotal")
    protected double anticipatedDirectTotal;
    @XmlElement(name = "AnticipatedIndirectTotal")
    protected double anticipatedIndirectTotal;
    @XmlElement(name = "AnticipatedTotal")
    protected double anticipatedTotal;
    @XmlElement(name = "ProjectEndDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar projectEndDate;

    /**
     * Gets the value of the projectStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProjectStartDate() {
        return projectStartDate;
    }

    /**
     * Sets the value of the projectStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProjectStartDate(XMLGregorianCalendar value) {
        this.projectStartDate = value;
    }

    /**
     * Gets the value of the anticipatedDirectTotal property.
     * 
     */
    public double getAnticipatedDirectTotal() {
        return anticipatedDirectTotal;
    }

    /**
     * Sets the value of the anticipatedDirectTotal property.
     * 
     */
    public void setAnticipatedDirectTotal(double value) {
        this.anticipatedDirectTotal = value;
    }

    /**
     * Gets the value of the anticipatedIndirectTotal property.
     * 
     */
    public double getAnticipatedIndirectTotal() {
        return anticipatedIndirectTotal;
    }

    /**
     * Sets the value of the anticipatedIndirectTotal property.
     * 
     */
    public void setAnticipatedIndirectTotal(double value) {
        this.anticipatedIndirectTotal = value;
    }

    /**
     * Gets the value of the anticipatedTotal property.
     * 
     */
    public double getAnticipatedTotal() {
        return anticipatedTotal;
    }

    /**
     * Sets the value of the anticipatedTotal property.
     * 
     */
    public void setAnticipatedTotal(double value) {
        this.anticipatedTotal = value;
    }

    /**
     * Gets the value of the projectEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProjectEndDate() {
        return projectEndDate;
    }

    /**
     * Sets the value of the projectEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProjectEndDate(XMLGregorianCalendar value) {
        this.projectEndDate = value;
    }

}
