//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 03:11:25 PM EST 
//


package edu.bu.kuali.kc.award.printing.awardnotice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AwardNoticeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AwardNoticeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BULogoPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AwardHeader" type="{http://printing.award.kc.kuali.bu.edu/awardnotice}AwardHeaderType"/>
 *         &lt;element name="ObligatedChangeHistory" type="{http://printing.award.kc.kuali.bu.edu/awardnotice}ObligatedChangeHistoryType" minOccurs="0"/>
 *         &lt;element name="ObligatedAmountTotal" type="{http://printing.award.kc.kuali.bu.edu/awardnotice}ObligatedAmountType" minOccurs="0"/>
 *         &lt;element name="AnticipatedAmountTotal" type="{http://printing.award.kc.kuali.bu.edu/awardnotice}AnticipatedAmountType" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://printing.award.kc.kuali.bu.edu/awardnotice}CommentsType" minOccurs="0"/>
 *         &lt;element name="TermsAndConditions" type="{http://printing.award.kc.kuali.bu.edu/awardnotice}TermsAndConditionsType" minOccurs="0"/>
 *         &lt;element name="ReportingRequirements" type="{http://printing.award.kc.kuali.bu.edu/awardnotice}ReportingRequirementsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AwardNoticeType", propOrder = {
    "buLogoPath",
    "awardHeader",
    "obligatedChangeHistory",
    "obligatedAmountTotal",
    "anticipatedAmountTotal",
    "comments",
    "termsAndConditions",
    "reportingRequirements"
})
public class AwardNoticeType {

    @XmlElement(name = "BULogoPath")
    protected String buLogoPath;
    @XmlElement(name = "AwardHeader", required = true)
    protected AwardHeaderType awardHeader;
    @XmlElement(name = "ObligatedChangeHistory")
    protected ObligatedChangeHistoryType obligatedChangeHistory;
    @XmlElement(name = "ObligatedAmountTotal")
    protected ObligatedAmountType obligatedAmountTotal;
    @XmlElement(name = "AnticipatedAmountTotal")
    protected AnticipatedAmountType anticipatedAmountTotal;
    @XmlElement(name = "Comments")
    protected CommentsType comments;
    @XmlElement(name = "TermsAndConditions")
    protected TermsAndConditionsType termsAndConditions;
    @XmlElement(name = "ReportingRequirements")
    protected ReportingRequirementsType reportingRequirements;

    /**
     * Gets the value of the buLogoPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBULogoPath() {
        return buLogoPath;
    }

    /**
     * Sets the value of the buLogoPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBULogoPath(String value) {
        this.buLogoPath = value;
    }

    /**
     * Gets the value of the awardHeader property.
     * 
     * @return
     *     possible object is
     *     {@link AwardHeaderType }
     *     
     */
    public AwardHeaderType getAwardHeader() {
        return awardHeader;
    }

    /**
     * Sets the value of the awardHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link AwardHeaderType }
     *     
     */
    public void setAwardHeader(AwardHeaderType value) {
        this.awardHeader = value;
    }

    /**
     * Gets the value of the obligatedChangeHistory property.
     * 
     * @return
     *     possible object is
     *     {@link ObligatedChangeHistoryType }
     *     
     */
    public ObligatedChangeHistoryType getObligatedChangeHistory() {
        return obligatedChangeHistory;
    }

    /**
     * Sets the value of the obligatedChangeHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObligatedChangeHistoryType }
     *     
     */
    public void setObligatedChangeHistory(ObligatedChangeHistoryType value) {
        this.obligatedChangeHistory = value;
    }

    /**
     * Gets the value of the obligatedAmountTotal property.
     * 
     * @return
     *     possible object is
     *     {@link ObligatedAmountType }
     *     
     */
    public ObligatedAmountType getObligatedAmountTotal() {
        return obligatedAmountTotal;
    }

    /**
     * Sets the value of the obligatedAmountTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObligatedAmountType }
     *     
     */
    public void setObligatedAmountTotal(ObligatedAmountType value) {
        this.obligatedAmountTotal = value;
    }

    /**
     * Gets the value of the anticipatedAmountTotal property.
     * 
     * @return
     *     possible object is
     *     {@link AnticipatedAmountType }
     *     
     */
    public AnticipatedAmountType getAnticipatedAmountTotal() {
        return anticipatedAmountTotal;
    }

    /**
     * Sets the value of the anticipatedAmountTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnticipatedAmountType }
     *     
     */
    public void setAnticipatedAmountTotal(AnticipatedAmountType value) {
        this.anticipatedAmountTotal = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link CommentsType }
     *     
     */
    public CommentsType getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentsType }
     *     
     */
    public void setComments(CommentsType value) {
        this.comments = value;
    }

    /**
     * Gets the value of the termsAndConditions property.
     * 
     * @return
     *     possible object is
     *     {@link TermsAndConditionsType }
     *     
     */
    public TermsAndConditionsType getTermsAndConditions() {
        return termsAndConditions;
    }

    /**
     * Sets the value of the termsAndConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermsAndConditionsType }
     *     
     */
    public void setTermsAndConditions(TermsAndConditionsType value) {
        this.termsAndConditions = value;
    }

    /**
     * Gets the value of the reportingRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingRequirementsType }
     *     
     */
    public ReportingRequirementsType getReportingRequirements() {
        return reportingRequirements;
    }

    /**
     * Sets the value of the reportingRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingRequirementsType }
     *     
     */
    public void setReportingRequirements(ReportingRequirementsType value) {
        this.reportingRequirements = value;
    }

}
