//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 03:11:25 PM EST 
//


package edu.bu.kuali.kc.award.printing.awardnotice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.bu.kuali.kc.award.printing.awardnotice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AwardNotice_QNAME = new QName("http://printing.award.kc.kuali.bu.edu/awardnotice", "AwardNotice");
    private final static QName _InvestigatorUnitsTypeUnitAdministratorAdministratorName_QNAME = new QName("http://printing.award.kc.kuali.bu.edu/awardnotice", "AdministratorName");
    private final static QName _InvestigatorUnitsTypeUnitAdministratorUnitAdministratorTypeCode_QNAME = new QName("http://printing.award.kc.kuali.bu.edu/awardnotice", "UnitAdministratorTypeCode");
    private final static QName _InvestigatorUnitsTypeUnitAdministratorAdministrator_QNAME = new QName("http://printing.award.kc.kuali.bu.edu/awardnotice", "Administrator");
    private final static QName _InvestigatorUnitsTypeOtherIndividualToNotify_QNAME = new QName("http://printing.award.kc.kuali.bu.edu/awardnotice", "OtherIndividualToNotify");
    private final static QName _InvestigatorUnitsTypeDeanVpName_QNAME = new QName("http://printing.award.kc.kuali.bu.edu/awardnotice", "DeanVpName");
    private final static QName _InvestigatorUnitsTypeUnitHeadName_QNAME = new QName("http://printing.award.kc.kuali.bu.edu/awardnotice", "UnitHeadName");
    private final static QName _InvestigatorUnitsTypeOtherIndividualToNotifyName_QNAME = new QName("http://printing.award.kc.kuali.bu.edu/awardnotice", "OtherIndividualToNotifyName");
    private final static QName _InvestigatorUnitsTypeAdministrativeOfficerName_QNAME = new QName("http://printing.award.kc.kuali.bu.edu/awardnotice", "AdministrativeOfficerName");
    private final static QName _InvestigatorUnitsTypeDeanVp_QNAME = new QName("http://printing.award.kc.kuali.bu.edu/awardnotice", "DeanVp");
    private final static QName _InvestigatorUnitsTypeAdministrativeOfficer_QNAME = new QName("http://printing.award.kc.kuali.bu.edu/awardnotice", "AdministrativeOfficer");
    private final static QName _InvestigatorUnitsTypeUnitHead_QNAME = new QName("http://printing.award.kc.kuali.bu.edu/awardnotice", "UnitHead");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.bu.kuali.kc.award.printing.awardnotice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReportingRequirementType }
     * 
     */
    public ReportingRequirementType createReportingRequirementType() {
        return new ReportingRequirementType();
    }

    /**
     * Create an instance of {@link ObligatedChangeType }
     * 
     */
    public ObligatedChangeType createObligatedChangeType() {
        return new ObligatedChangeType();
    }

    /**
     * Create an instance of {@link AwardHeaderType }
     * 
     */
    public AwardHeaderType createAwardHeaderType() {
        return new AwardHeaderType();
    }

    /**
     * Create an instance of {@link DepartmentAdminsType }
     * 
     */
    public DepartmentAdminsType createDepartmentAdminsType() {
        return new DepartmentAdminsType();
    }

    /**
     * Create an instance of {@link AdminType }
     * 
     */
    public AdminType createAdminType() {
        return new AdminType();
    }

    /**
     * Create an instance of {@link InvestigatorType }
     * 
     */
    public InvestigatorType createInvestigatorType() {
        return new InvestigatorType();
    }

    /**
     * Create an instance of {@link AnticipatedAmountType }
     * 
     */
    public AnticipatedAmountType createAnticipatedAmountType() {
        return new AnticipatedAmountType();
    }

    /**
     * Create an instance of {@link CommentsType }
     * 
     */
    public CommentsType createCommentsType() {
        return new CommentsType();
    }

    /**
     * Create an instance of {@link TermTxtType }
     * 
     */
    public TermTxtType createTermTxtType() {
        return new TermTxtType();
    }

    /**
     * Create an instance of {@link AwardInvestigatorsType }
     * 
     */
    public AwardInvestigatorsType createAwardInvestigatorsType() {
        return new AwardInvestigatorsType();
    }

    /**
     * Create an instance of {@link InvestigatorUnitsType.UnitAdministrator }
     * 
     */
    public InvestigatorUnitsType.UnitAdministrator createInvestigatorUnitsTypeUnitAdministrator() {
        return new InvestigatorUnitsType.UnitAdministrator();
    }

    /**
     * Create an instance of {@link TermAndConditionType }
     * 
     */
    public TermAndConditionType createTermAndConditionType() {
        return new TermAndConditionType();
    }

    /**
     * Create an instance of {@link CommentType }
     * 
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link FundsCenterInfoType }
     * 
     */
    public FundsCenterInfoType createFundsCenterInfoType() {
        return new FundsCenterInfoType();
    }

    /**
     * Create an instance of {@link ObligatedAmountType }
     * 
     */
    public ObligatedAmountType createObligatedAmountType() {
        return new ObligatedAmountType();
    }

    /**
     * Create an instance of {@link InvestigatorUnitsType }
     * 
     */
    public InvestigatorUnitsType createInvestigatorUnitsType() {
        return new InvestigatorUnitsType();
    }

    /**
     * Create an instance of {@link TermsType }
     * 
     */
    public TermsType createTermsType() {
        return new TermsType();
    }

    /**
     * Create an instance of {@link OSPAdminsType }
     * 
     */
    public OSPAdminsType createOSPAdminsType() {
        return new OSPAdminsType();
    }

    /**
     * Create an instance of {@link TermsAndConditionsType }
     * 
     */
    public TermsAndConditionsType createTermsAndConditionsType() {
        return new TermsAndConditionsType();
    }

    /**
     * Create an instance of {@link AwardNoticeType }
     * 
     */
    public AwardNoticeType createAwardNoticeType() {
        return new AwardNoticeType();
    }

    /**
     * Create an instance of {@link ObligatedChangeHistoryType }
     * 
     */
    public ObligatedChangeHistoryType createObligatedChangeHistoryType() {
        return new ObligatedChangeHistoryType();
    }

    /**
     * Create an instance of {@link PAFOAdminsType }
     * 
     */
    public PAFOAdminsType createPAFOAdminsType() {
        return new PAFOAdminsType();
    }

    /**
     * Create an instance of {@link AdminsType }
     * 
     */
    public AdminsType createAdminsType() {
        return new AdminsType();
    }

    /**
     * Create an instance of {@link ReportingRequirementsType }
     * 
     */
    public ReportingRequirementsType createReportingRequirementsType() {
        return new ReportingRequirementsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardNoticeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", name = "AwardNotice")
    public JAXBElement<AwardNoticeType> createAwardNotice(AwardNoticeType value) {
        return new JAXBElement<AwardNoticeType>(_AwardNotice_QNAME, AwardNoticeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", name = "AdministratorName", scope = InvestigatorUnitsType.UnitAdministrator.class)
    public JAXBElement<String> createInvestigatorUnitsTypeUnitAdministratorAdministratorName(String value) {
        return new JAXBElement<String>(_InvestigatorUnitsTypeUnitAdministratorAdministratorName_QNAME, String.class, InvestigatorUnitsType.UnitAdministrator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", name = "UnitAdministratorTypeCode", scope = InvestigatorUnitsType.UnitAdministrator.class)
    public JAXBElement<Integer> createInvestigatorUnitsTypeUnitAdministratorUnitAdministratorTypeCode(Integer value) {
        return new JAXBElement<Integer>(_InvestigatorUnitsTypeUnitAdministratorUnitAdministratorTypeCode_QNAME, Integer.class, InvestigatorUnitsType.UnitAdministrator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", name = "Administrator", scope = InvestigatorUnitsType.UnitAdministrator.class)
    public JAXBElement<String> createInvestigatorUnitsTypeUnitAdministratorAdministrator(String value) {
        return new JAXBElement<String>(_InvestigatorUnitsTypeUnitAdministratorAdministrator_QNAME, String.class, InvestigatorUnitsType.UnitAdministrator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", name = "OtherIndividualToNotify", scope = InvestigatorUnitsType.class)
    public JAXBElement<String> createInvestigatorUnitsTypeOtherIndividualToNotify(String value) {
        return new JAXBElement<String>(_InvestigatorUnitsTypeOtherIndividualToNotify_QNAME, String.class, InvestigatorUnitsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", name = "DeanVpName", scope = InvestigatorUnitsType.class)
    public JAXBElement<String> createInvestigatorUnitsTypeDeanVpName(String value) {
        return new JAXBElement<String>(_InvestigatorUnitsTypeDeanVpName_QNAME, String.class, InvestigatorUnitsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", name = "UnitHeadName", scope = InvestigatorUnitsType.class)
    public JAXBElement<String> createInvestigatorUnitsTypeUnitHeadName(String value) {
        return new JAXBElement<String>(_InvestigatorUnitsTypeUnitHeadName_QNAME, String.class, InvestigatorUnitsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", name = "OtherIndividualToNotifyName", scope = InvestigatorUnitsType.class)
    public JAXBElement<String> createInvestigatorUnitsTypeOtherIndividualToNotifyName(String value) {
        return new JAXBElement<String>(_InvestigatorUnitsTypeOtherIndividualToNotifyName_QNAME, String.class, InvestigatorUnitsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", name = "AdministrativeOfficerName", scope = InvestigatorUnitsType.class)
    public JAXBElement<String> createInvestigatorUnitsTypeAdministrativeOfficerName(String value) {
        return new JAXBElement<String>(_InvestigatorUnitsTypeAdministrativeOfficerName_QNAME, String.class, InvestigatorUnitsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", name = "DeanVp", scope = InvestigatorUnitsType.class)
    public JAXBElement<String> createInvestigatorUnitsTypeDeanVp(String value) {
        return new JAXBElement<String>(_InvestigatorUnitsTypeDeanVp_QNAME, String.class, InvestigatorUnitsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", name = "AdministrativeOfficer", scope = InvestigatorUnitsType.class)
    public JAXBElement<String> createInvestigatorUnitsTypeAdministrativeOfficer(String value) {
        return new JAXBElement<String>(_InvestigatorUnitsTypeAdministrativeOfficer_QNAME, String.class, InvestigatorUnitsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", name = "UnitHead", scope = InvestigatorUnitsType.class)
    public JAXBElement<String> createInvestigatorUnitsTypeUnitHead(String value) {
        return new JAXBElement<String>(_InvestigatorUnitsTypeUnitHead_QNAME, String.class, InvestigatorUnitsType.class, value);
    }

}
