//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 03:11:25 PM EST 
//


package edu.bu.kuali.kc.award.printing.awardnotice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObligatedChangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObligatedChangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InetrnalOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LegacySourceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FnARate" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ObligatedChangeDirect" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ObligatedChangeIndirect" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TotalChange" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObligatedChangeType", propOrder = {
    "inetrnalOrderNumber",
    "description",
    "legacySourceNumber",
    "pi",
    "fnARate",
    "obligatedChangeDirect",
    "obligatedChangeIndirect",
    "totalChange"
})
public class ObligatedChangeType {

    @XmlElement(name = "InetrnalOrderNumber", required = true)
    protected String inetrnalOrderNumber;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "LegacySourceNumber", required = true)
    protected String legacySourceNumber;
    @XmlElement(name = "PI", required = true)
    protected String pi;
    @XmlElement(name = "FnARate")
    protected double fnARate;
    @XmlElement(name = "ObligatedChangeDirect")
    protected double obligatedChangeDirect;
    @XmlElement(name = "ObligatedChangeIndirect")
    protected double obligatedChangeIndirect;
    @XmlElement(name = "TotalChange")
    protected double totalChange;

    /**
     * Gets the value of the inetrnalOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInetrnalOrderNumber() {
        return inetrnalOrderNumber;
    }

    /**
     * Sets the value of the inetrnalOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInetrnalOrderNumber(String value) {
        this.inetrnalOrderNumber = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the legacySourceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegacySourceNumber() {
        return legacySourceNumber;
    }

    /**
     * Sets the value of the legacySourceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegacySourceNumber(String value) {
        this.legacySourceNumber = value;
    }

    /**
     * Gets the value of the pi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPI() {
        return pi;
    }

    /**
     * Sets the value of the pi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPI(String value) {
        this.pi = value;
    }

    /**
     * Gets the value of the fnARate property.
     * 
     */
    public double getFnARate() {
        return fnARate;
    }

    /**
     * Sets the value of the fnARate property.
     * 
     */
    public void setFnARate(double value) {
        this.fnARate = value;
    }

    /**
     * Gets the value of the obligatedChangeDirect property.
     * 
     */
    public double getObligatedChangeDirect() {
        return obligatedChangeDirect;
    }

    /**
     * Sets the value of the obligatedChangeDirect property.
     * 
     */
    public void setObligatedChangeDirect(double value) {
        this.obligatedChangeDirect = value;
    }

    /**
     * Gets the value of the obligatedChangeIndirect property.
     * 
     */
    public double getObligatedChangeIndirect() {
        return obligatedChangeIndirect;
    }

    /**
     * Sets the value of the obligatedChangeIndirect property.
     * 
     */
    public void setObligatedChangeIndirect(double value) {
        this.obligatedChangeIndirect = value;
    }

    /**
     * Gets the value of the totalChange property.
     * 
     */
    public double getTotalChange() {
        return totalChange;
    }

    /**
     * Sets the value of the totalChange property.
     * 
     */
    public void setTotalChange(double value) {
        this.totalChange = value;
    }

}
