//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 03:11:25 PM EST 
//


package edu.bu.kuali.kc.award.printing.awardnotice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObligatedChangeHistoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObligatedChangeHistoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ObligatedChange" type="{http://printing.award.kc.kuali.bu.edu/awardnotice}ObligatedChangeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FnARateTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ObligatedChangeDirectTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ObligatedChangeIndrectTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="TotalChangeTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObligatedChangeHistoryType", propOrder = {
    "obligatedChange",
    "fnARateTotal",
    "obligatedChangeDirectTotal",
    "obligatedChangeIndrectTotal",
    "totalChangeTotal"
})
public class ObligatedChangeHistoryType {

    @XmlElement(name = "ObligatedChange")
    protected List<ObligatedChangeType> obligatedChange;
    @XmlElement(name = "FnARateTotal")
    protected Double fnARateTotal;
    @XmlElement(name = "ObligatedChangeDirectTotal")
    protected Double obligatedChangeDirectTotal;
    @XmlElement(name = "ObligatedChangeIndrectTotal")
    protected Double obligatedChangeIndrectTotal;
    @XmlElement(name = "TotalChangeTotal")
    protected Double totalChangeTotal;

    /**
     * Gets the value of the obligatedChange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obligatedChange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObligatedChange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObligatedChangeType }
     * 
     * 
     */
    public List<ObligatedChangeType> getObligatedChange() {
        if (obligatedChange == null) {
            obligatedChange = new ArrayList<ObligatedChangeType>();
        }
        return this.obligatedChange;
    }

    /**
     * Gets the value of the fnARateTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFnARateTotal() {
        return fnARateTotal;
    }

    /**
     * Sets the value of the fnARateTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFnARateTotal(Double value) {
        this.fnARateTotal = value;
    }

    /**
     * Gets the value of the obligatedChangeDirectTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getObligatedChangeDirectTotal() {
        return obligatedChangeDirectTotal;
    }

    /**
     * Sets the value of the obligatedChangeDirectTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setObligatedChangeDirectTotal(Double value) {
        this.obligatedChangeDirectTotal = value;
    }

    /**
     * Gets the value of the obligatedChangeIndrectTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getObligatedChangeIndrectTotal() {
        return obligatedChangeIndrectTotal;
    }

    /**
     * Sets the value of the obligatedChangeIndrectTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setObligatedChangeIndrectTotal(Double value) {
        this.obligatedChangeIndrectTotal = value;
    }

    /**
     * Gets the value of the totalChangeTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTotalChangeTotal() {
        return totalChangeTotal;
    }

    /**
     * Sets the value of the totalChangeTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTotalChangeTotal(Double value) {
        this.totalChangeTotal = value;
    }

}
