//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 03:11:25 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://printing.award.kc.kuali.bu.edu/awardnotice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.bu.kuali.kc.award.printing.awardnotice;
